[package]
name = "spivak-calculus"
version = "0.1"
lean_version = "leanprover-community/lean:3.26.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "d0456d3b6cd6a7002f1d629779cff82430f86f12"}
